external-dns:

  
  
  domainFilters:
    - kubrix.stackit.run
  global:
#    imagePullSecrets:
#      - name: image-pull-secret
    security:
      allowInsecureImages: true
  provider:
    name: webhook
    webhook:
#      args:
#      - --api-port=8080
      image:
        repository: ghcr.io/stackitcloud/external-dns-stackit-webhook
        tag: v0.3.2       
      env:
        - name: LOG_LEVEL
          value: debug # reduce in production
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: external-dns-webhook
              key: AUTH_TOKEN
        - name: PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: external-dns-webhook
              key: PROJECT_ID
      livenessProbe:
        failureThreshold: 2
        httpGet:
          path: /healthz
          port: 8888
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 6
        httpGet:
          path: /healthz
          port: 8888
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
  txtOwnerId: kubrix-production
  
