vui:
  global:
    veleroNamespace: velero
    kubernetesClusterDomain: cluster.local
    clusterName: "kubriX--demo"
    nextPublicLoggerEnabled: false

  apiConfig:
    apiEnableDocumentation: "1"
    k8SInClusterMode: "True"
    origins1: 'https://velero-ui.kubrix.stackit.run'
    veleroCliVersion: v1.14.0
    existingSecret: velero-ui-credential

  uiIngress:
    enabled: true
    host: velero-ui.kubrix.stackit.run
    ingressClassName: nginx
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/ttl: "60"
        cert-manager.io/cluster-issuer: letsencrypt-prod
    spec:
      tls:
        - secretName: velero-ui-tls
          hosts:
            - velero-ui.kubrix.stackit.run
  
  uiNp: # NodePort
    enabled: false
    ip: ""
    apiPort: "30001"
    uiPort: "30002"

